### ISSUE TITLE
Create a Contact Page

### ISSUE THREAD

**Issue by reinkaoss** [reinkaoss/React-Student-Hub-App#1]
Resources:
https://zoom.us/rec/play/SoZX5AXYLvKsduNhAW8UnX1GGj3XUZyfktaGC84dRVrrthVOxa6eO1rebVfBFWPTSK-r4N7UUmPvMTn3.5iUoyJ0Pm4v8_lJI?startTime=1675751339000

**Comment by hollusam** [comment]
Done
